name: Update AutoMod Configuration

on:
  push:
    branches:
      - main
    paths:
      - 'automod/automoderator.yml'

jobs:
  update-automod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PRAW
        run: pip install praw

      - name: Update AutoMod Configuration on Reddit
        run: python update_automod.py
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          SUBREDDIT_NAME: ${{ secrets.SUBREDDIT_NAME }}
